# ---------------------------------------------------------------
# Jekyll & Global Configuration
## Docs: https://jekyllrb.com/docs/configuration/
# ---------------------------------------------------------------

# Site
title: Dr. Ryu's Neuroscience and AI
subtitle:
description: AI, Machine learning, Neuroscience, Evolution
author: Benjamin Ryu
# Support language: de, en, fr-FR, id, ja, ko, pt-BR, pt, ru, zh-Hans, zh-hk, zh-tw
language: en
date_format: '%Y-%m-%d'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com' and baseurl as '/child'
url:
baseurl:
permalink: pretty

# Pagination
paginate: 10

# Handling Reading
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "README_en.md"]

# Code Highlighter
highlighter: rouge

#### Markdown Processors
markdown: kramdown
kramdown:
    input: GFM

# Default Attributes
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Atom feed
feed:
  path: atom.xml

# Plugins
plugins:
 - jekyll-sitemap
 - jekyll-feed

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

favicon: /assets/favicon.ico
keywords: "DrRyu, Neuroscience, AI"
rss:
authoricon: heart
copyright: true

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

canonical: true
seo: false
index_with_subtitle: false

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: /
  journal: /categories/Journal/
  ai_agent: /categories/AI%20Agent/
  openclaw: /categories/OpenClaw/
  archives: /archives/
  tags: /tags/

menu_icons:
  enable: true
  home: home
  about: user
  journal: book
  ai_agent: robot
  openclaw: terminal
  categories: th
  schedule: calendar
  tags: tags
  archives: archive
  sitemap: sitemap
  commonweal: heartbeat

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

scheme: Muse

# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------
font:
  enable: true
  host:
  global:
    external: true
    family: Lato
  headings:
    external: true
    family:
  posts:
    external: true
    family:
  logo:
    external: true
    family:
    size:
  codes:
    external: true
    family:
    size:

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

social:
  Github: https://github.com/lonehades

social_icons:
  enable: true
  GitHub: github
  Twitter: twitter
  Weibo: weibo

avatar: /assets/images/ryu.jpg

toc:
  enable: true
  number: true
  wrap: false

sidebar:
  position: left
  display: always
  offset: 12
  offset_float: 0

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

scroll_to_more: true
save_scroll: false
excerpt_description: true
auto_excerpt:
  enable: false
  length: 150

post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true

post_wordcount:
  item_text: true
  wordcount: false
  min2read: false
  separated_meta: true

post_copyright:
  enable: false
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

custom_logo:
  enabled: false
  image:

highlight_theme: normal

# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

mathjax:
  enable: true
  per_page: true
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

han: false

disqus:
  enable: true
  shortname: lonehades
  count: true
  hide: false

google_analytics: UA-146224397-1

duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0

facebook_sdk:
  enable: false
facebook_comments_plugin:
  enable: false
vkontakte_api:
  enable: false
rating:
  enable: false
leancloud_visitors:
  enable: false

busuanzi_count:
  enable: true
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:

baidu_push: false

calendar:
  enable: false

algolia_search:
  enable: false

local_search:
  enable: false

exturl: false

# ---------------------------------------------------------------
# Motion Settings
# ---------------------------------------------------------------

use_motion: true
fancybox: true
pace: false
pace_theme: pace-theme-minimal
canvas_nest: false
three_waves: false
canvas_lines: false
canvas_sphere: false
canvas_ribbon: false

# ---------------------------------------------------------------
# Assets & Theme version
# ---------------------------------------------------------------

css: assets/css
js: assets/js
images: assets/images
version: 5.1.1
